version: '2'
services:
  back:
    image: socialementcompetents/backathon
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test
      - EMAIL_HOST=mailcatcher
      - EMAIL_PORT=25
      - NODE_ENV=production
    depends_on: 
      - mongo
      - mailcatcher
    networks:
      - mail
      - data
      - front

  front:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://back:3000/graphql
      - SERVER_URL_SUB=wh://back:3000/subscriptions
    ports:
      - 8080:80
    depends_on: 
      - back
    networks:
      - front

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - data

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 1080:80
    networks:
      - mail

networks:
  front:
  data:
  mail: