export default {
  SET_LOGIN_STATUS: 'SET_LOGIN_STATUS',
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  REQUEST_CONVERSATIONS: 'REQUEST_CONVERSATIONS',
  RECEIVED_CONVERSATIONS: 'RECEIVED_CONVERSATIONS'
}
