export default {
  SET_LOGIN_STATUS: 'SET_LOGIN_STATUS',
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  LOG_OUT: 'LOG_OUT',
  REQUEST_CONVERSATIONS: 'REQUEST_CONVERSATIONS',
  RECEIVED_CONVERSATIONS: 'RECEIVED_CONVERSATIONS',
  REQUEST_LOGIN: 'REQUEST_LOGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  RECEIVED_LOGIN: 'RECEIVED_LOGIN',
  REQUEST_ADD_MESSAGE: 'REQUEST_ADD_MESSAGE',
  RECEIVED_ADD_MESSAGE: 'RECEIVED_ADD_MESSAGE',
  ADD_MESSAGE_ERROR: 'ADD_MESSAGE_ERROR',
  SELECT_CONVERSATION: 'SELECT_CONVERSATION'
}
