export default {
  SET_LOGIN_STATUS: 'SET_LOGIN_STATUS',
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  LOG_OUT: 'LOG_OUT',
  REQUEST_CONVERSATIONS: 'REQUEST_CONVERSATIONS',
  RECEIVED_CONVERSATIONS: 'RECEIVED_CONVERSATIONS',
  REQUEST_LOGIN: 'REQUEST_LOGIN',
  RECEIVED_LOGIN: 'RECEIVED_LOGIN'
}
